<?php
/**
 * @file qasstl_redirect.module
 */

/**
 * Implements hook_init().
 */
function qasstl_redirect_init() {
  // Redirect to special page
  if (drupal_is_front_page()) {
    foreach (array('qas-school.com', 'qasschoolstl.org', 'qasschoolstl.com') as $host_name) {
      if (strstr($_SERVER['HTTP_HOST'], $host_name)) {
  	    drupal_goto('http://qasstl.org/content/queen-all-saints-school');
  	  }
    }
  }
  elseif (substr($_SERVER['HTTP_HOST'], 0, 4) === 'www.') {
    header('Location: http'.(isset($_SERVER['HTTPS']) && $_SERVER['HTTPS']=='on' ? 's':'').'://' . substr($_SERVER['HTTP_HOST'], 4).$_SERVER['REQUEST_URI']);
    exit;
  }
}